name: movie_box
description: An application to checkout Movies and TV Shows and manage watch-list.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.12
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  go_router: ^3.0.7
  google_fonts: ^2.3.2
  injectable: ^1.5.3
  json_serializable: ^6.1.6

dev_dependencies:
  build_runner: null
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: null

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/launcher_icon.png"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/png/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
